version: "3.3"
services:
  app:
    build: .
    restart: always
    image: boristax/comby-fasades:v0.2.4
    ports:
      - "5555:5000"
    command: npm run start
    volumes: 
      - combi-db:/app/src/server/database
volumes:
  combi-db:
      external: true