version: "3.3"
services:
  app:
    build: .
    restart: always
    image: boristax/wardrobes:v0.3.5
    ports:
      - "5555:5555"
      - "8888:8888"
    command: npm run start
    volumes: 
      - wardrobes-db:/app/src/server/database
volumes:
  wardrobes-db:
      external: true