version: "3.3"
services:
  app:
    build: .
    restart: always
    image: boristax/wardrobes:v0.3.2
    ports:
      - "5555:5000"
      - "8888:8888"
    command: npm run start
    volumes: 
      - combi-db:/app/src/server/database
volumes:
  combi-db:
      external: true